version: "3.4"

services:
  flaskweb:
    image: flaskweb
    build:
      context: flask-web
      # dockerfile: flask-web/Dockerfile
    ports:
      - 5000:5000
    environment:
      - CRONKITE_HOST=http://cronkiteservice:8000
  cronkiteservice:
    image: cronkiteservice
    build:
      context: cronkite-service
      # dockerfile: cronkite-service/Dockerfile
    ports:
      - 8000
    command: "--host 0.0.0.0"
    volumes:
      - ".:/app:rw"
      - "./cronkite-service/data:/data2:rw"
  db:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=supersecret
